In [3]:
# 1回目
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

import pandas as pd

df_train = pd.read_csv('data/train.csv')
df_holidays_events = pd.read_csv('data/holidays_events.csv')
df_oil = pd.read_csv('data/oil.csv')
df_stores = pd.read_csv('data/stores.csv')
df_transactions = pd.read_csv('data/transactions.csv')
df_test = pd.read_csv('data/test.csv')
df_sample_submission = pd.read_csv('data/sample_submission.csv')

train_merged = pd.merge(df_train, df_stores, on ='store_nbr')
train_merged = train_merged.sort_values(["store_nbr","family","date"])
train_merged = train_merged.astype({"store_nbr":'str', "family":'str', "city":'str',
                          "state":'str', "type":'str', "cluster":'str'})
display(train_merged.head())
 
def label_encoding(data):
    '''
    カテゴリーをLabelエンコーディング
    '''
    LE = LabelEncoder()
    LE.fit_transform(data.values)
    return LE.fit_transform(data.values)

# カテゴリーをLabelエンコーディング
train_merged["date_E"] = label_encoding(train_merged["date"])
df_test["date_E"] = label_encoding(df_test["date"])

# 特徴量とターゲット変数を分ける（train_mergedデータ）
X_df_train = train_merged[["date_E","store_nbr","onpromotion"]]
y_df_train = train_merged["sales"]

# 線形回帰モデルを作成して訓練
model = RandomForestRegressor(random_state=42)
model.fit(X_df_train, y_df_train)

# テストデータの特徴量で予測
X_test = df_test[["date_E","store_nbr","onpromotion"]]
y_pred = model.predict(X_test)
print(y_pred)

# 予測結果をCSVファイルとして保存
df_sample_submission[1] = y_pred
df_sample_submission.to_csv("submit/submission1.csv", index=None, header=None)

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13
33,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13
66,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13
99,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13
132,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13

[   0.            0.         1031.91966667 ... 1953.833422   4038.76591
  228.48811797]

In [1]:
# 2回目
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

import pandas as pd

df_train = pd.read_csv('data/train.csv')
df_holidays_events = pd.read_csv('data/holidays_events.csv')
df_oil = pd.read_csv('data/oil.csv')
df_stores = pd.read_csv('data/stores.csv')
df_transactions = pd.read_csv('data/transactions.csv')
df_test = pd.read_csv('data/test.csv')
df_sample_submission = pd.read_csv('data/sample_submission.csv')

train_merged = pd.merge(df_train, df_stores, on ='store_nbr')
train_merged = train_merged.sort_values(["store_nbr","family","date"])
train_merged = train_merged.astype({"store_nbr":'str', "family":'str', "city":'str',
                          "state":'str', "type":'str', "cluster":'str'})
display(train_merged.head())
 
def label_encoding(data):
    '''
    カテゴリーをLabelエンコーディング
    '''
    LE = LabelEncoder()
    LE.fit_transform(data.values)
    return LE.fit_transform(data.values)

# カテゴリーをLabelエンコーディング
train_merged["date_E"] = label_encoding(train_merged["date"])
df_test["date_E"] = label_encoding(df_test["date"])

# 特徴量とターゲット変数を分ける（train_mergedデータ）
X_df_train = train_merged[["date_E","store_nbr","onpromotion"]]
y_df_train = train_merged["sales"]

# 線形回帰モデルを作成して訓練
model = RandomForestRegressor(random_state=42)
model.fit(X_df_train, y_df_train)

# テストデータの特徴量で予測
X_test = df_test[["date_E","store_nbr","onpromotion"]]
y_pred = model.predict(X_test)
print(y_pred)

# 予測結果をCSVファイルとして保存
# df_sample_submission[1] = y_pred
# df_sample_submission.to_csv("submit/submission2.csv", index=None, header=None)

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13
33,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13
66,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13
99,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13
132,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13

[   0.            0.         1031.91966667 ... 1953.833422   4038.76591
  228.48811797]